#!/usr/bin/env bash

folder="$HOME/Pictures"
path="$folder/$(date +'%Y-%m-%d-%H%M%S').png"

ANS=$(echo -e "\n\n" | rofi -theme ~/.local/share/rofi-buttons.rasi -font "RobotoMono 300" -dmenu -i)
if [ "$ANS" == "" ] ; then
        args="--delay=0.5 --select --highlight --color=0.85,0.87,0.91,0.2"
elif [ "$ANS" == "" ] ; then
        args="--delay=1 --window=$(xdotool getactivewindow)"
elif [ "$ANS" == "" ] ; then
        args="--delay=1"
else
        exit 1
fi
maim --hidecursor --quiet --quality=3 --format='png' $args "$path" && {
        notify-send "Screenshot saved as $path"

        xclip -selection clipboard -target 'image/png' -in "$path"
}
