#!/usr/bin/env sh

power_off=''
reboot=''
lock=''


case "$chosen" in
    "$power_off")
        poweroff
        ;;

    "$reboot")
        reboot
        ;;

    "$lock")
        lock
        ;;

    *) exit 1 ;;
esac
