#!/usr/bin/env bash
# Gives a rofi prompt to mount unmounted drives.

mountusb() {
    chosen="$(echo "$usbdrives" | rofi -dmenu -i -p "Mount which drive" | awk '{print $1}')"
    mount="$(udisksctl mount -b "$chosen")"
    notify-send "$mount"
}

usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v -e nvme | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
    echo "No USB drives detected." && notify-send "No drives detected" && exit
else
    echo "USB drive(s) detected."
    mountusb
fi
