{ pkgs, ... }:

{
  programs.lf = {
    enable = true;

    commands = {
        extract = ''''${{
            set -f
            case $f in
              *.tar.bz2 | *.tar.xz | *.tbz2) tar xvjf "$archive" ;;
              *.tar.gz | *.tgz) tar xvzf "$archive" ;;
              *.lzma) unlzma "$archive" ;;
              *.bz2) bunzip2 "$archive" ;;
              *.rar) unrar x -ad "$archive" ;;
              *.gz) gunzip "$archive" ;;
              *.tar) tar xvf "$archive" ;;
              *.zip) unzip "$archive" ;;
              *.Z) uncompress "$archive" ;;
              *.7z) 7z x "$archive" ;;
              *.xz) unxz "$archive" ;;
              *.exe) cabextract "$archive" ;;
            esac
        }}'';
        find = ''''${{
            f=$(fd | fzf)
                if [ -d $f ]; then
                    cmd="cd"
                else
                    cmd="select"
                fi
                lf -remote "send $id $cmd $f"
        }}'';
    };

    keybindings = {
        "/" = "search";
        "<c-f>" = "find";
        "<c-h>" = "set hidden!";
        "D" = "delete";
        "gg" = "top";
        "G" = "bottom";
        "gh" = "cd ~";
        "g/" = "cd /";
        "gm" = "cd /run/media/jack";
    };

    settings = {
      dircounts = true;
      dirfirst = true;
      drawbox = true;
      icons = true;
      ignorecase = true;
      incsearch = true;
      scrolloff = 2;
    };
  };

  home.sessionVariables = {
      LF_ICONS = ''
          ln=:\
          or=:\
          tw=t:\
          ow=:\
          st=t:\
          di=:\
          pi=p:\
          so=s:\
          bd=b:\
          cd=c:\
          su=u:\
          sg=g:\
          ex=:\
          fi=:\
          *.styl=:\
          *.sass=:\
          *.scss=:\
          *.htm=:\
          *.html=:\
          *.slim=:\
          *.haml=:\
          *.ejs=:\
          *.css=:\
          *.less=:\
          *.md=:\
          *.mdx=:\
          *.markdown=:\
          *.rmd=:\
          *.json=:\
          *.webmanifest=:\
          *.js=:\
          *.mjs=:\
          *.jsx=:\
          *.rb=:\
          *.gemspec=:\
          *.rake=:\
          *.php=:\
          *.py=:\
          *.pyc=:\
          *.pyo=:\
          *.pyd=:\
          *.coffee=:\
          *.mustache=:\
          *.hbs=:\
          *.conf=:\
          *.ini=:\
          *.yml=:\
          *.yaml=:\
          *.toml=:\
          *.bat=:\
          *.mk=:\
          *.jpg=:\
          *.jpeg=:\
          *.bmp=:\
          *.png=:\
          *.webp=:\
          *.gif=:\
          *.ico=:\
          *.twig=:\
          *.cpp=:\
          *.c++=:\
          *.cxx=:\
          *.cc=:\
          *.cp=:\
          *.c=:\
          *.cs=:\
          *.h=:\
          *.hh=:\
          *.hpp=:\
          *.hxx=:\
          *.hs=:\
          *.lhs=:\
          *.nix=:\
          *.lua=:\
          *.java=:\
          *.sh=:\
          *.fish=:\
          *.bash=:\
          *.zsh=:\
          *.ksh=:\
          *.csh=:\
          *.awk=:\
          *.ps1=:\
          *.ml=λ:\
          *.mli=λ:\
          *.diff=:\
          *.db=:\
          *.sql=:\
          *.dump=:\
          *.clj=:\
          *.cljc=:\
          *.cljs=:\
          *.edn=:\
          *.scala=:\
          *.go=:\
          *.dart=:\
          *.xul=:\
          *.sln=:\
          *.suo=:\
          *.pl=:\
          *.pm=:\
          *.t=:\
          *.rss=:\
          '*.f#'=:\
          *.fsscript=:\
          *.fsx=:\
          *.fs=:\
          *.fsi=:\
          *.rs=:\
          *.rlib=:\
          *.d=:\
          *.erl=:\
          *.hrl=:\
          *.ex=:\
          *.exs=:\
          *.eex=:\
          *.leex=:\
          *.heex=:\
          *.vim=:\
          *.ai=:\
          *.psd=:\
          *.psb=:\
          *.ts=:\
          *.tsx=:\
          *.jl=:\
          *.pp=:\
          *.vue=:\
          *.elm=:\
          *.swift=:\
          *.xcplayground=:\
          *.tex=ﭨ:\
          *.r=ﳒ:\
          *.rproj=鉶:\
          *.sol=ﲹ:\
          *.pem=:\
          *gruntfile.coffee=:\
          *gruntfile.js=:\
          *gruntfile.ls=:\
          *gulpfile.coffee=:\
          *gulpfile.js=:\
          *gulpfile.ls=:\
          *mix.lock=:\
          *dropbox=:\
          *.ds_store=:\
          *.gitconfig=:\
          *.gitignore=:\
          *.gitattributes=:\
          *.gitlab-ci.yml=:\
          *.bashrc=:\
          *.zshrc=:\
          *.zshenv=:\
          *.zprofile=:\
          *.vimrc=:\
          *.gvimrc=:\
          *_vimrc=:\
          *_gvimrc=:\
          *.bashprofile=:\
          *favicon.ico=:\
          *license=:\
          *node_modules=:\
          *react.jsx=:\
          *procfile=:\
          *dockerfile=:\
          *docker-compose.yml=:\
          *rakefile=:\
          *config.ru=:\
          *gemfile=:\
          *makefile=:\
          *cmakelists.txt=:\
          *robots.txt=ﮧ:\
          *Gruntfile.coffee=:\
          *Gruntfile.js=:\
          *Gruntfile.ls=:\
          *Gulpfile.coffee=:\
          *Gulpfile.js=:\
          *Gulpfile.ls=:\
          *Dropbox=:\
          *.DS_Store=:\
          *LICENSE=:\
          *React.jsx=:\
          *Procfile=:\
          *Dockerfile=:\
          *Docker-compose.yml=:\
          *Rakefile=:\
          *Gemfile=:\
          *Makefile=:\
          *CMakeLists.txt=:\
          *jquery.min.js=:\
          *angular.min.js=:\
          *backbone.min.js=:\
          *require.min.js=:\
          *vimrc=:\
          *.tar=:\
          *.tgz=:\
          *.arc=:\
          *.arj=:\
          *.taz=:\
          *.lha=:\
          *.lz4=:\
          *.lzh=:\
          *.lzma=:\
          *.tlz=:\
          *.txz=:\
          *.tzo=:\
          *.t7z=:\
          *.zip=:\
          *.z=:\
          *.dz=:\
          *.gz=:\
          *.lrz=:\
          *.lz=:\
          *.lzo=:\
          *.xz=:\
          *.zst=:\
          *.tzst=:\
          *.bz2=:\
          *.bz=:\
          *.tbz=:\
          *.tbz2=:\
          *.tz=:\
          *.deb=:\
          *.rpm=:\
          *.jar=:\
          *.war=:\
          *.ear=:\
          *.sar=:\
          *.rar=:\
          *.alz=:\
          *.ace=:\
          *.zoo=:\
          *.cpio=:\
          *.7z=:\
          *.rz=:\
          *.cab=:\
          *.wim=:\
          *.swm=:\
          *.dwm=:\
          *.esd=:\
          *.jpg=:\
          *.jpeg=:\
          *.gif=:\
          *.bmp=:\
          *.pbm=:\
          *.pgm=:\
          *.ppm=:\
          *.tga=:\
          *.xbm=:\
          *.xpm=:\
          *.tif=:\
          *.tiff=:\
          *.png=:\
          *.svg=:\
          *.svgz=:\
          *.xcf=:\
          *.aac=󰝚:\
          *.au=󰝚:\
          *.flac=󰝚:\
          *.m4a=󰝚:\
          *.mid=󰝚:\
          *.midi=󰝚:\
          *.mka=󰝚:\
          *.mp3=󰝚:\
          *.mpc=󰝚:\
          *.ogg=󰝚:\
          *.ra=󰝚:\
          *.wav=󰝚:\
          *.oga=󰝚:\
          *.opus=󰝚:\
          *.spx=󰝚:\
          *.xspf=󰝚:\
          *.amv=󰕧:\
          *.avi=󰕧:\
          *.flv=󰕧:\
          *.m4v=󰕧:\
          *.mkv=󰕧:\
          *.mov=󰕧:\
          *.mp4=󰕧:\
          *.mpg=󰕧:\
          *.mpeg=󰕧:\
          *.vob=󰕧:\
          *.webm=󰕧:\
          *.wmv=󰕧:\
          *.pdf=:\
      '';
    LF_COLORS = ''
          ln=01;36:\
          or=31;01:\
          tw=34:\
          ow=34:\
          st=01;34:\
          di=01;34:\
          pi=33:\
          so=01;35:\
          bd=33;01:\
          cd=33;01:\
          su=01;32:\
          sg=01;32:\
          ex=01;32:\
          fi=00:\
          *.tar=01;31:\
          *.tgz=01;31:\
          *.arc=01;31:\
          *.arj=01;31:\
          *.taz=01;31:\
          *.lha=01;31:\
          *.lz4=01;31:\
          *.lzh=01;31:\
          *.lzma=01;31:\
          *.tlz=01;31:\
          *.txz=01;31:\
          *.tzo=01;31:\
          *.t7z=01;31:\
          *.zip=01;31:\
          *.z=01;31:\
          *.dz=01;31:\
          *.gz=01;31:\
          *.lrz=01;31:\
          *.lz=01;31:\
          *.lzo=01;31:\
          *.xz=01;31:\
          *.zst=01;31:\
          *.tzst=01;31:\
          *.bz2=01;31:\
          *.bz=01;31:\
          *.tbz=01;31:\
          *.tbz2=01;31:\
          *.tz=01;31:\
          *.deb=01;31:\
          *.rpm=01;31:\
          *.jar=01;31:\
          *.war=01;31:\
          *.ear=01;31:\
          *.sar=01;31:\
          *.rar=01;31:\
          *.alz=01;31:\
          *.ace=01;31:\
          *.zoo=01;31:\
          *.cpio=01;31:\
          *.7z=01;31:\
          *.rz=01;31:\
          *.cab=01;31:\
          *.wim=01;31:\
          *.swm=01;31:\
          *.dwm=01;31:\
          *.esd=01;31:\
          *.jpg=01;35:\
          *.jpeg=01;35:\
          *.mjpg=01;35:\
          *.mjpeg=01;35:\
          *.gif=01;35:\
          *.bmp=01;35:\
          *.pbm=01;35:\
          *.pgm=01;35:\
          *.ppm=01;35:\
          *.tga=01;35:\
          *.xbm=01;35:\
          *.xpm=01;35:\
          *.tif=01;35:\
          *.tiff=01;35:\
          *.png=01;35:\
          *.svg=01;35:\
          *.svgz=01;35:\
          *.mng=01;35:\
          *.pcx=01;35:\
          *.mov=01;35:\
          *.mpg=01;35:\
          *.mpeg=01;35:\
          *.m2v=01;35:\
          *.mkv=01;35:\
          *.webm=01;35:\
          *.ogm=01;35:\
          *.mp4=01;35:\
          *.m4v=01;35:\
          *.mp4v=01;35:\
          *.vob=01;35:\
          *.qt=01;35:\
          *.nuv=01;35:\
          *.wmv=01;35:\
          *.asf=01;35:\
          *.rm=01;35:\
          *.rmvb=01;35:\
          *.flc=01;35:\
          *.avi=01;35:\
          *.fli=01;35:\
          *.flv=01;35:\
          *.gl=01;35:\
          *.dl=01;35:\
          *.xcf=01;35:\
          *.xwd=01;35:\
          *.yuv=01;35:\
          *.cgm=01;35:\
          *.emf=01;35:\
          *.ogv=01;35:\
          *.ogx=01;35:\
          *.aac=00;36:\
          *.au=00;36:\
          *.flac=00;36:\
          *.m4a=00;36:\
          *.mid=00;36:\
          *.midi=00;36:\
          *.mka=00;36:\
          *.mp3=00;36:\
          *.mpc=00;36:\
          *.ogg=00;36:\
          *.ra=00;36:\
          *.wav=00;36:\
          *.oga=00;36:\
          *.opus=00;36:\
          *.spx=00;36:\
          *.xspf=00;36:\
      '';
  };
}
